services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: transactionworkflow-sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - transactionworkflow_sql_data:/var/opt/mssql

volumes:
  transactionworkflow_sql_data:
